### ISSUE TITLE
可高度自定义的底部对话框 BottomSheetDialog

### ISSUE THREAD

**Issue by Krosxx** [OpenBug-Android/OpenBug-Android#8]
> 使用BottomSheet，支持滚动布局，同时底部布局不会因BottomSheet未显示全部内容而隐藏。

|![](https://github.com/Vove7/BottomDialog/raw/android-x/screenshots/s0.jpg)|![](https://github.com/Vove7/BottomDialog/raw/android-x/screenshots/s2.jpg)|![](https://github.com/Vove7/BottomDialog/raw/android-x/screenshots/s1.jpg)|
|-|-|-|

**Comment by KunMinX** [comment]
@Vove7 
请贴一下项目链接 …

**Comment by Krosxx** [comment]
忘了 哈哈
https://github.com/Vove7/BottomDialog
